/**
 * Secrets Consumers — config-file write side.
 *
 * After rotation, write the new value to each consumer's config file.
 * Atomic writes (write tmp → fsync → rename), mode 600 on every file.
 * Reload each consumer (nginx -s reload, SIGHUP for openclaw-webhook).
 * Audit log per consumer.
 *
 * Agent/VPN-agnostic: the env var name that maps to each consumer is
 * configurable via `SECRETS_CONSUMER_ENV_VAR` (default `OLLAMA_TAILSCALE_AUTH_TOKEN`
 * for backward compatibility). Snippet filenames are generic (no vendor name).
 *
 * @author Keridz ⚙️
 */

import { spawn } from 'node:child_process';
import { resolve } from 'node:path';
import { atomicWriteFile } from './secrets-loader';

// ─── Types ─────────────────────────────────────────────────────────────

export interface ConsumerConfig {
  name: string;
  path: string;
  reloadMethod: 'sighup' | 'nginx-reload' | 'none';
  reloadTarget?: string; // PID file path or service name
  format: 'env' | 'nginx-conf';
  envVarName: string;
}

export interface ConsumerWriteResult {
  consumer: string;
  path: string;
  result: 'ok' | 'error';
  error?: string;
  reloaded: boolean;
  reloadError?: string;
}

// ─── Consumer Registry ────────────────────────────────────────────────

/**
 * Env var name that maps to each consumer's secret. Configurable via
 * `SECRETS_CONSUMER_ENV_VAR`; defaults to the legacy name for backward
 * compatibility with existing deployments.
 */
const CONSUMER_ENV_VAR =
  process.env.SECRETS_CONSUMER_ENV_VAR || 'OLLAMA_TAILSCALE_AUTH_TOKEN';

const CONSUMERS: ConsumerConfig[] = [
  {
    name: 'openclaw-webhook',
    path: '/etc/openclaw-webhook/secrets.env',
    reloadMethod: 'sighup',
    reloadTarget: '/var/run/openclaw-webhook.pid',
    format: 'env',
    envVarName: CONSUMER_ENV_VAR,
  },
  {
    name: 'nginx-11435',
    path: '/etc/nginx/snippets/auth-11435.conf',
    reloadMethod: 'nginx-reload',
    format: 'nginx-conf',
    envVarName: CONSUMER_ENV_VAR,
  },
  {
    name: 'nginx-8080',
    path: '/etc/nginx/snippets/auth-8080.conf',
    reloadMethod: 'nginx-reload',
    format: 'nginx-conf',
    envVarName: CONSUMER_ENV_VAR,
  },
];

/**
 * Get the list of registered consumers.
 */
export function getConsumers(): ConsumerConfig[] {
  return [...CONSUMERS];
}

/**
 * Get the list of consumer names (for API responses).
 */
export function getConsumerNames(): string[] {
  return CONSUMERS.map((c) => c.name);
}

/**
 * Format the secret value for the consumer's config file format.
 * Never logs the value — formatting is in-memory only.
 */
function formatValue(consumer: ConsumerConfig, secretName: string, secretValue: string): string {
  if (consumer.format === 'env') {
    return `${secretName}=${secretValue}\n`;
  }
  if (consumer.format === 'nginx-conf') {
    // nginx snippet: set the auth token as a variable
    return `# Auto-generated by kill-switch secrets-loader. DO NOT EDIT.\n` +
      `# Rotated at ${new Date().toISOString()}\n` +
      `set $${secretName.toLowerCase()} "${secretValue}";\n`;
  }
  return `${secretName}=${secretValue}\n`;
}

/**
 * Write the new secret value to a single consumer's config file.
 * Atomic write, mode 600, never logs the value.
 */
async function writeToConsumer(
  consumer: ConsumerConfig,
  secretName: string,
  secretValue: string,
): Promise<ConsumerWriteResult> {
  const content = formatValue(consumer, secretName, secretValue);

  try {
    await atomicWriteFile(consumer.path, content);
  } catch (err) {
    return {
      consumer: consumer.name,
      path: consumer.path,
      result: 'error',
      error: (err as Error).message,
      reloaded: false,
    };
  }

  // Reload the consumer
  let reloaded = false;
  let reloadError: string | undefined;

  if (consumer.reloadMethod === 'nginx-reload') {
    try {
      await runCommand('nginx', ['-s', 'reload']);
      reloaded = true;
    } catch (err) {
      reloadError = (err as Error).message;
    }
  } else if (consumer.reloadMethod === 'sighup') {
    try {
      const pid = await readPidFile(consumer.reloadTarget || '');
      if (pid) {
        process.kill(pid, 'SIGHUP');
        reloaded = true;
      } else {
        reloadError = 'PID file empty or not found';
      }
    } catch (err) {
      reloadError = (err as Error).message;
    }
  }

  return {
    consumer: consumer.name,
    path: consumer.path,
    result: 'ok',
    reloaded,
    reloadError,
  };
}

/**
 * Write the new secret value to ALL consumers.
 * Returns per-consumer results.
 */
export async function writeToAllConsumers(
  secretName: string,
  secretValue: string,
): Promise<ConsumerWriteResult[]> {
  const results: ConsumerWriteResult[] = [];
  for (const consumer of CONSUMERS) {
    const result = await writeToConsumer(consumer, secretName, secretValue);
    results.push(result);
  }
  return results;
}

/**
 * Run a shell command and return on completion.
 */
function runCommand(cmd: string, args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, { stdio: 'ignore', detached: false });
    proc.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${cmd} exited with code ${code}`));
    });
    proc.on('error', reject);
  });
}

/**
 * Read a PID from a PID file.
 */
async function readPidFile(pidPath: string): Promise<number | null> {
  try {
    const { readFile } = await import('node:fs/promises');
    const content = await readFile(pidPath, 'utf-8');
    const pid = parseInt(content.trim(), 10);
    return isNaN(pid) ? null : pid;
  } catch {
    return null;
  }
}