// Generated by ts-to-zod
import { z } from "zod";
import { Json } from "./database.types";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const clusterGpusRowSchema = z.object({
  cluster_id: z.string(),
  cores: z.number(),
  created_at: z.string().nullable(),
  id: z.string(),
  memory_gb: z.number(),
  model: z.string(),
  updated_at: z.string().nullable(),
});

export const clusterGpusInsertSchema = z.object({
  cluster_id: z.string(),
  cores: z.number(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  memory_gb: z.number(),
  model: z.string(),
  updated_at: z.string().optional().nullable(),
});

export const clusterGpusUpdateSchema = z.object({
  cluster_id: z.string().optional(),
  cores: z.number().optional(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  memory_gb: z.number().optional(),
  model: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const complianceAuditLogRowSchema = z.object({
  dpu_id: z.string(),
  id: z.string(),
  intent_hash: z.string(),
  proof_data: jsonSchema,
  redline_violated: z.string().nullable(),
  timestamp: z.string(),
});

export const complianceAuditLogInsertSchema = z.object({
  dpu_id: z.string(),
  id: z.string().optional(),
  intent_hash: z.string(),
  proof_data: jsonSchema.optional(),
  redline_violated: z.string().optional().nullable(),
  timestamp: z.string().optional(),
});

export const complianceAuditLogUpdateSchema = z.object({
  dpu_id: z.string().optional(),
  id: z.string().optional(),
  intent_hash: z.string().optional(),
  proof_data: jsonSchema.optional(),
  redline_violated: z.string().optional().nullable(),
  timestamp: z.string().optional(),
});

export const dpuClustersRowSchema = z.object({
  avg_latency: z.number().nullable(),
  created_at: z.string().nullable(),
  gpus: z.number(),
  id: z.string(),
  last_heartbeat: z.string().nullable(),
  last_seen: z.string().nullable(),
  location: z.string(),
  name: z.string(),
  policy_violations: z.number().nullable(),
  slug: z.string(),
  status: z.string(),
  total_requests: z.number().nullable(),
  updated_at: z.string().nullable(),
  uptime: z.number().nullable(),
});

export const dpuClustersInsertSchema = z.object({
  avg_latency: z.number().optional().nullable(),
  created_at: z.string().optional().nullable(),
  gpus: z.number().optional(),
  id: z.string().optional(),
  last_heartbeat: z.string().optional().nullable(),
  last_seen: z.string().optional().nullable(),
  location: z.string(),
  name: z.string(),
  policy_violations: z.number().optional().nullable(),
  slug: z.string(),
  status: z.string().optional(),
  total_requests: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  uptime: z.number().optional().nullable(),
});

export const dpuClustersUpdateSchema = z.object({
  avg_latency: z.number().optional().nullable(),
  created_at: z.string().optional().nullable(),
  gpus: z.number().optional(),
  id: z.string().optional(),
  last_heartbeat: z.string().optional().nullable(),
  last_seen: z.string().optional().nullable(),
  location: z.string().optional(),
  name: z.string().optional(),
  policy_violations: z.number().optional().nullable(),
  slug: z.string().optional(),
  status: z.string().optional(),
  total_requests: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  uptime: z.number().optional().nullable(),
});

export const publicAuditTrailRowSchema = z.object({
  dpu_id: z.string().nullable(),
  id: z.string().nullable(),
  intent_hash: z.string().nullable(),
  public_hash: z.string().nullable(),
  timestamp: z.string().nullable(),
  zkp_commitment: z.string().nullable(),
});

export const publicAuditTrailInsertSchema = z.object({
  dpu_id: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  intent_hash: z.string().optional().nullable(),
  public_hash: z.never().optional(),
  timestamp: z.string().optional().nullable(),
  zkp_commitment: z.never().optional(),
});

export const publicAuditTrailUpdateSchema = z.object({
  dpu_id: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  intent_hash: z.string().optional().nullable(),
  public_hash: z.never().optional(),
  timestamp: z.string().optional().nullable(),
  zkp_commitment: z.never().optional(),
});

export const recentViolationsRowSchema = z.object({
  attestation: z.string().nullable(),
  dpu_id: z.string().nullable(),
  id: z.string().nullable(),
  intent_hash: z.string().nullable(),
  redline_violated: z.string().nullable(),
  timestamp: z.string().nullable(),
  zkp_commitment: z.string().nullable(),
});

export const recentViolationsInsertSchema = z.object({
  attestation: z.never().optional(),
  dpu_id: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  intent_hash: z.string().optional().nullable(),
  redline_violated: z.string().optional().nullable(),
  timestamp: z.string().optional().nullable(),
  zkp_commitment: z.never().optional(),
});

export const recentViolationsUpdateSchema = z.object({
  attestation: z.never().optional(),
  dpu_id: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  intent_hash: z.string().optional().nullable(),
  redline_violated: z.string().optional().nullable(),
  timestamp: z.string().optional().nullable(),
  zkp_commitment: z.never().optional(),
});
