# Redis Node 3 - Cluster Config
bind 0.0.0.0
port 6379
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
cluster-announce-ip redis-node-3
cluster-announce-port 6379
cluster-announce-bus-port 16379
appendonly yes
appendfilename "appendonly.aof"
maxmemory 256mb
maxmemory-policy allkeys-lru