/**
 * Dignity Verifier Dashboard — LlamaIndex Augmentation Guide
 *
 * Explains how LlamaIndex performs semantic augmentation in this framework:
 * full pipeline, configuration parameters, best practices, and a glossary.
 */

import { PageShell } from "@/components/page-shell";
import { PageHeader } from "@/components/page-header";
import { DocSection } from "@/components/doc-section";
import { DocTable } from "@/components/doc-table";

/* ─── Pipeline (deep dive) ────────────────────────────────────── */

const PIPELINE_STEPS = [
  {
    step: "1 · Index",
    desc: "Build a vector index over the seed dataset using nomic-embed-text-v2-moe (local, F16, 512 context, 768-dim embeddings).",
  },
  {
    step: "2 · Retrieve",
    desc: "For each seed example, fetch top-5 semantically similar examples by cosine similarity.",
  },
  {
    step: "3 · Paraphrase",
    desc: "The teacher model (deepseek-v4-flash:cloud) generates paraphrases and variations of the (prompt, output) pair.",
  },
  {
    step: "4 · Verify",
    desc: "Check each augmented example against the teacher's verdict — if the teacher gives a different verdict for the paraphrased example, reject it.",
  },
  {
    step: "5 · Dedupe",
    desc: "Drop examples with cosine similarity > 0.92 to any existing example (prevents near-duplicates).",
  },
] as const;

/* ─── Configuration parameters (deep dive) ────────────────────── */

const CONFIG_PARAMS = [
  {
    param: "top_k",
    desc: "Number of neighbors to retrieve per seed example.",
    recommended: "5",
    notes: "Higher = more context but more noise. Lower = faster but might miss relevant examples.",
  },
  {
    param: "similarity_threshold",
    desc: "Minimum cosine similarity for retrieval.",
    recommended: "0.7",
    notes: "Below this threshold, an example is not relevant enough to retrieve.",
  },
  {
    param: "teacher_model",
    desc: "The model used to generate paraphrases and verify verdicts.",
    recommended: "deepseek-v4-flash:cloud (primary), glm-5.2:cloud (fallback)",
    notes: "Must be an allowed cloud model; the student is local qwen2.5:0.5b.",
  },
  {
    param: "temperature",
    desc: "Sampling temperature for the teacher during paraphrase generation.",
    recommended: "0.7",
    notes: "High enough for variety, low enough for coherence.",
  },
  {
    param: "max_paraphrases_per_seed",
    desc: "Number of paraphrases generated per seed example.",
    recommended: "3",
    notes: "Higher = more data but more verification cost.",
  },
] as const;

/* ─── Best practices ──────────────────────────────────────────── */

const BEST_PRACTICES = [
  {
    title: "Verify every verdict",
    desc: "Never include unverified examples — check each augmented example's verdict against the teacher before inclusion.",
  },
  {
    title: "Monitor class distribution",
    desc: "After augmentation, check that no single class dominates. Rebalance if needed.",
  },
  {
    title: "Log all augmentation decisions",
    desc: "Record accepted/rejected examples for reproducibility and audit.",
  },
  {
    title: "Re-index after adding seed data",
    desc: "The index must reflect the current dataset — rebuild it whenever new seed examples are added.",
  },
  {
    title: "Use one embedding model",
    desc: "Use the same embedding model for retrieval and deduplication to keep similarity scores consistent.",
  },
] as const;

/* ─── Glossary ────────────────────────────────────────────────── */

const GLOSSARY_TERMS = [
  { term: "LlamaIndex", def: "A data framework for building retrieval and augmentation pipelines." },
  { term: "Vector index", def: "A data structure storing embeddings for fast similarity search." },
  { term: "Embedding", def: "A dense vector representation of text capturing semantic meaning." },
  { term: "Cosine similarity", def: "A measure of vector similarity used for retrieval and deduplication." },
  { term: "Semantic retrieval", def: "Finding examples by meaning rather than exact text match." },
  { term: "Paraphrase", def: "A reworded version of a seed example generated by the teacher." },
  { term: "Teacher model", def: "A large model (deepseek-v4-flash:cloud) that generates paraphrases and verdicts." },
  { term: "Student model", def: "The smaller model (qwen2.5:0.5b) being fine-tuned from the teacher's labels." },
  { term: "Augmentation", def: "Growing the training set by generating diverse paraphrases of seed examples." },
  { term: "Deduplication", def: "Removing near-duplicate examples (cosine > 0.92) to keep signal diverse." },
  { term: "nomic-embed-text", def: "The local embedding model used for retrieval and deduplication." },
  { term: "top-k", def: "The number of nearest neighbors retrieved per query." },
  { term: "Similarity threshold", def: "The minimum cosine similarity for an example to be considered relevant." },
  { term: "JSONL", def: "JSON Lines — a text format where each line is a self-contained JSON object." },
] as const;

/* ─── References ──────────────────────────────────────────────── */

const REFERENCES = [
  { label: "LlamaIndex documentation", href: "https://docs.llamaindex.ai" },
  { label: "nomic-embed-text model card", href: "https://huggingface.co/nomic-ai/nomic-embed-text-v2-moe" },
] as const;

export function LlamaIndexGuidePage() {
  return (
    <PageShell active="/docs">
      <PageHeader
        eyebrow="Docs · Augmentation"
        title="LlamaIndex Augmentation Guide"
        description="How semantic augmentation works in this framework: the full pipeline, configuration parameters, best practices, and a glossary."
      />

      {/* ─── What LlamaIndex does ────────────────────────────── */}
      <DocSection
        number="1"
        title="What LlamaIndex does here"
        lead="LlamaIndex provides the semantic augmentation layer: it indexes the seed dataset and generates diverse paraphrases to grow the training set."
      >
        <p className="text-sm text-slate-400">
          The framework uses LlamaIndex to turn the hand-curated seed set (~270 examples) into a
          larger, more diverse training set (target 500+). By retrieving semantically similar
          examples and paraphrasing them with the teacher model, augmentation adds coverage of the
          classification boundary without hand-writing every example.
        </p>
      </DocSection>

      {/* ─── Pipeline flow ───────────────────────────────────── */}
      <DocSection number="2" title="Pipeline Flow (Deep Dive)">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {PIPELINE_STEPS.map((item) => (
            <div key={item.step} className="rounded-xl border border-slate-800 bg-slate-900 p-5">
              <p className="text-sm font-semibold text-emerald-300">{item.step}</p>
              <p className="mt-2 text-xs text-slate-400">{item.desc}</p>
            </div>
          ))}
        </div>
        <p className="text-sm text-slate-400">
          The pipeline targets <span className="font-semibold text-emerald-300">270 seed → 500+ augmented</span>{" "}
          examples. Every augmented example passes through verification and deduplication before it
          is accepted into the training set.
        </p>
      </DocSection>

      {/* ─── Configuration parameters ────────────────────────── */}
      <DocSection number="3" title="Configuration Parameters (Deep Dive)">
        <DocTable
          headers={["Parameter", "What it does", "Recommended", "Notes"]}
          rows={CONFIG_PARAMS.map((p) => [p.param, p.desc, p.recommended, p.notes])}
        />
      </DocSection>

      {/* ─── Best practices ──────────────────────────────────── */}
      <DocSection number="4" title="Best Practices for Augmentation Quality">
        <div className="grid gap-4 sm:grid-cols-2">
          {BEST_PRACTICES.map((item) => (
            <div key={item.title} className="rounded-xl border border-slate-800 bg-slate-900 p-5">
              <h3 className="text-sm font-semibold text-emerald-300">{item.title}</h3>
              <p className="mt-2 text-sm text-slate-400">{item.desc}</p>
            </div>
          ))}
        </div>
      </DocSection>

      {/* ─── Glossary ────────────────────────────────────────── */}
      <DocSection
        number="5"
        title="Glossary"
        lead="Key terms used in this guide. See the full glossary for the complete framework vocabulary."
      >
        <dl className="grid gap-4 sm:grid-cols-2">
          {GLOSSARY_TERMS.map((item) => (
            <div key={item.term} className="rounded-lg border border-slate-800 bg-slate-900 p-4">
              <dt className="font-mono text-sm font-semibold text-emerald-300">{item.term}</dt>
              <dd className="mt-1 text-sm text-slate-400">{item.def}</dd>
            </div>
          ))}
        </dl>
      </DocSection>

      {/* ─── References ──────────────────────────────────────── */}
      <DocSection number="6" title="References">
        <ul className="list-disc space-y-2 pl-5 text-sm text-slate-400">
          {REFERENCES.map((ref) => (
            <li key={ref.href}>
              <a
                href={ref.href}
                target="_blank"
                rel="noopener noreferrer"
                className="text-emerald-400 underline transition hover:text-emerald-300"
              >
                {ref.label}
              </a>
            </li>
          ))}
        </ul>
      </DocSection>
    </PageShell>
  );
}

export default LlamaIndexGuidePage;
